version: "3.9"

services:
  client:
    container_name: loficlient
    image: client
    build:
      context: ./client
    depends_on:
      - api
      - nginx
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - ./client/src:/client/src
    restart: always
  api:
    container_name: lofiapi
    image: api
    build:
      context: ./api
    depends_on:
      - db
      - nginx
    ports:
      - 3001:3001
    command: npm run watch
    volumes:
      - ./api/server.js:/api/server.js
      - ./api/utils/:/api/utils/
      - ./api/config/:/api/config/
      - ./api/routes/:/api/routes/
    environment:
      NODE_ENV: development
    restart: always
  db:
    container_name: lofidb
    image: db
    build:
      context: ./db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: renaud
      POSTGRES_DB: lofi
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always
  nginx:
    container_name: lofinginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

